os: linux
dist: focal
language: perl
perl:
  - "5.32"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y r-base libgd-dev"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

before_script:
  - "make install_auto"

script:
  - "make test"
  - "make clean"

notifications:
  email:
    on_failure: always
